# 'bundle exec jekyll serve'

title: RedBot 3D Printer
description: >-
  Instructions how to build the 3D Printer
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
highlighter: rouge
host: 192.168.1.212

exclude:
  - "*.bat"
  - Gemfile
  - Gemfile.lock

sass:
  #style: compressed

langs:
  - code: en
    name: English

  - code: ru
    name: Русский

defaults:
  lang: ru