# 'bundle exec jekyll serve'

title: RedBot 3D Printer
description: >-
  Instructions how to build the 3D Printer
default_lang: "ru"
links:
  github: "https://github.com/NickRimmer/RedBot/tree/gh-pages"
  support: "#"
  telegram:
    ru: https://t.me/redbot_ru
    en: https://t.me/redbot_en

# Build settings
markdown: kramdown
highlighter: rouge

exclude:
  - "*.bat"
  - Gemfile
  - Gemfile.lock

sass:
  #style: compressed

defaults:
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "pages/ru"
      type: "pages"
    values:
      lang: "ru"
  -
    scope:
      path: "pages/en"
      type: "pages"
    values:
      lang: "en"